# Generated by Django 4.2.3 on 2023-07-13 15:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('client_name', models.CharField(max_length=300)),
                ('client_id_no', models.CharField(max_length=10)),
                ('client_phone_no', models.CharField(max_length=10)),
                ('collateral_name', models.CharField(max_length=200)),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('loan_period', models.IntegerField(default=7)),
                ('repayment_date', models.DateTimeField(default=datetime.datetime(2023, 7, 20, 15, 37, 21, 255557, tzinfo=datetime.timezone.utc))),
                ('loan_amount', models.FloatField()),
                ('interest_rate', models.IntegerField(default=30)),
                ('repayment_amount', models.FloatField()),
                ('loan_status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=100)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Collaterals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collateral_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('collateral_name', models.CharField(max_length=200)),
                ('held_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('collection_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Collected', 'Collected'), ('Not Collected', 'Not Collected')], max_length=100)),
                ('loan_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='waveapp.loans')),
            ],
        ),
    ]
