# Generated by Django 4.2.3 on 2023-07-13 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waveapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='interest_rate',
            field=models.FloatField(default=0.3),
        ),
        migrations.AlterField(
            model_name='loans',
            name='repayment_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 20, 19, 20, 19, 693373, tzinfo=datetime.timezone.utc)),
        ),
    ]
