# Generated by Django 4.2.3 on 2023-07-13 19:40

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('waveapp', '0002_alter_loans_interest_rate_alter_loans_repayment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaterals',
            old_name='loan_id',
            new_name='loan',
        ),
        migrations.AddField(
            model_name='loans',
            name='collateral_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='paid_on',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='repayment_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 20, 19, 40, 20, 160882, tzinfo=datetime.timezone.utc)),
        ),
    ]
