# Generated by Django 4.2.3 on 2023-07-13 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waveapp', '0003_rename_loan_id_collaterals_loan_loans_collateral_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaterals',
            options={'get_latest_by': ['held_on']},
        ),
        migrations.AlterModelOptions(
            name='loans',
            options={'get_latest_by': ['created_on']},
        ),
        migrations.AlterField(
            model_name='loans',
            name='repayment_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 20, 19, 56, 13, 633033, tzinfo=datetime.timezone.utc)),
        ),
    ]
