# Generated by Django 4.2.3 on 2023-07-14 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waveapp', '0004_alter_collaterals_options_alter_loans_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='default_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loans',
            name='repayment_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 21, 14, 21, 49, 699175, tzinfo=datetime.timezone.utc)),
        ),
    ]
