# Generated by Django 4.2.3 on 2023-07-14 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waveapp', '0006_loans_repayment_due_alter_loans_repayment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loans',
            name='repayment_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 21, 16, 22, 30, 827644, tzinfo=datetime.timezone.utc)),
        ),
    ]
