# Generated by Django 4.2.3 on 2023-07-21 12:19

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('waveapp', '0007_loans_paid_alter_loans_repayment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaterals',
            name='collected_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loans',
            name='repayment_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 28, 12, 19, 37, 747689, tzinfo=datetime.timezone.utc)),
        ),
    ]
