# Generated by Django 4.2.3 on 2023-07-22 14:23

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('waveapp', '0009_loans_defaulted_on_alter_loans_repayment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaterals',
            name='confiscated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collaterals',
            name='confiscated_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loans',
            name='repayment_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 29, 14, 23, 0, 353420, tzinfo=datetime.timezone.utc)),
        ),
    ]
