# Generated by Django 4.2.3 on 2023-07-22 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waveapp', '0010_collaterals_confiscated_collaterals_confiscated_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loans',
            old_name='repayment_due',
            new_name='overdue',
        ),
        migrations.AlterField(
            model_name='loans',
            name='repayment_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 29, 14, 39, 51, 695321, tzinfo=datetime.timezone.utc)),
        ),
    ]
