# Generated by Django 4.2.3 on 2023-07-22 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waveapp', '0011_rename_repayment_due_loans_overdue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='paid_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='remaining_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='repayment_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 29, 15, 28, 0, 134348, tzinfo=datetime.timezone.utc)),
        ),
    ]
