# Generated by Django 4.2.3 on 2023-07-26 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waveapp', '0012_loans_paid_amount_loans_remaining_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='loan_extended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loans',
            name='loan_extensions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loans',
            name='repayment_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 2, 7, 20, 42, 51802, tzinfo=datetime.timezone.utc)),
        ),
    ]
