# Generated by Django 4.2.3 on 2023-07-26 07:51

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('waveapp', '0013_loans_loan_extended_loans_loan_extensions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='extended_on',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(default=django.utils.timezone.now), blank=True, default=[datetime.datetime(2023, 7, 26, 7, 51, 52, 491536, tzinfo=datetime.timezone.utc)], size=None),
        ),
        migrations.AlterField(
            model_name='loans',
            name='repayment_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 2, 7, 51, 52, 491369, tzinfo=datetime.timezone.utc)),
        ),
    ]
